# Generated by Django 4.1.4 on 2023-01-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_product_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
