# Generated by Django 4.1.4 on 2023-01-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
